# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-13 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_store_date', models.DateTimeField(blank=True, null=True)),
                ('box_review_date', models.DateTimeField(blank=True, null=True)),
                ('box_contents', models.CharField(blank=True, max_length=300, null=True)),
                ('box_on_loan', models.BooleanField(default=False)),
                ('box_return_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Box',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Historicalbox',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('box_store_date', models.DateTimeField(blank=True, null=True)),
                ('box_review_date', models.DateTimeField(blank=True, null=True)),
                ('box_contents', models.CharField(blank=True, max_length=300, null=True)),
                ('box_on_loan', models.BooleanField(default=False)),
                ('box_return_date', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical box',
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicallocation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('loc_room', models.CharField(blank=True, max_length=20, null=True)),
                ('loc_section', models.IntegerField(blank=True, null=True)),
                ('loc_shelf', models.CharField(blank=True, max_length=4, null=True)),
                ('loc_date', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical location',
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicalproject',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_number', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('project_name', models.CharField(max_length=255, null=True)),
                ('project_date', models.DateTimeField(blank=True, null=True)),
                ('project_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical project',
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_room', models.CharField(blank=True, max_length=20, null=True)),
                ('loc_section', models.IntegerField(blank=True, null=True)),
                ('loc_shelf', models.CharField(blank=True, max_length=4, null=True)),
                ('loc_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('project_name', models.CharField(max_length=255, null=True)),
                ('project_date', models.DateTimeField(blank=True, null=True)),
                ('project_manager', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['project_number'],
                'db_table': 'Project',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserQueryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_history', models.CharField(blank=True, max_length=300, null=True)),
                ('date_searched', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Query_History',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='historicalbox',
            name='location_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory_management_app.location'),
        ),
        migrations.AddField(
            model_name='historicalbox',
            name='project_assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory_management_app.project'),
        ),
        migrations.AddField(
            model_name='box',
            name='location_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management_app.location'),
        ),
        migrations.AddField(
            model_name='box',
            name='project_assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management_app.project'),
        ),
    ]
