# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-13 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0003_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee Name',
        ),
    ]
