# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-22 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0016_auto_20181213_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='Location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management_app.Location'),
        ),
        migrations.AlterField(
            model_name='box',
            name='project_assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management_app.Project'),
        ),
        migrations.AlterField(
            model_name='historicalbox',
            name='Location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory_management_app.Location'),
        ),
        migrations.AlterField(
            model_name='historicalbox',
            name='project_assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory_management_app.Project'),
        ),
    ]
