# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-02-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_app', '0023_auto_20190210_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'managed': True, 'ordering': ['Location', 'project_assigned_to']},
        ),
        migrations.AlterField(
            model_name='box',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management_app.Location'),
        ),
        migrations.AlterField(
            model_name='box',
            name='project_assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_management_app.Project'),
        ),
        migrations.AlterField(
            model_name='historicalbox',
            name='Location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory_management_app.Location'),
        ),
        migrations.AlterField(
            model_name='historicalbox',
            name='project_assigned_to',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventory_management_app.Project'),
        ),
    ]
